package io.github.zaraporsche911cloud.reportingassistant.report.model;

public enum ReportType {
    FLEET_OVERVIEW,
    FUEL_CONSUMPTION,
    FUEL_EFFICIENCY,
    MILEAGE,
    DRIVER_PERFORMANCE,
    VEHICLE_AVAILABILITY,
    MAINTENANCE_STATUS,
    OVERDUE_MAINTENANCE,
    ANOMALIES,
    CRITICAL_ANOMALIES,
    TRIPS,
    OPERATING_COSTS,
    VEHICLE_UTILIZATION,
    MONTHLY_COMPARISON,
    PERIOD_COMPARISON,
    TOP_VEHICLES,
    TOP_DRIVERS,
    TREND_ANALYSIS
}
