import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Bot, Copy, Download, Menu, Play, Plus, Save, Send, Trash2, User } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useLocation, useSearchParams } from 'react-router-dom'
import { assistantApi, conversationApi, reportApi } from '../api'
import { downloadFile, getProblemMessage } from '../api/client'
import { ReportView } from '../components/ReportView'
import { useToast } from '../components/Toast'
import { Button, ErrorState, LoadingState, StatusBadge } from '../components/ui'
import type { GeneratedReport, Message } from '../types/api'

export function AssistantPage() {
  const [params, setParams] = useSearchParams()
  const location = useLocation()
  const queryClient = useQueryClient()
  const toast = useToast()
  const [question, setQuestion] = useState((location.state as { question?: string } | null)?.question ?? '')
  const [selectedId, setSelectedId] = useState<number | undefined>(() => Number(params.get('conversation')) || undefined)
  const [mobileHistory, setMobileHistory] = useState(false)
  const [optimisticQuestion, setOptimisticQuestion] = useState('')
  const [suggestions, setSuggestions] = useState<string[]>([])
  const conversations = useQuery({ queryKey: ['conversations'], queryFn: conversationApi.list })
  const details = useQuery({ queryKey: ['conversation', selectedId], queryFn: () => conversationApi.get(selectedId!), enabled: Boolean(selectedId) })
  const reportIds = useMemo(() => details.data?.messages.map((message) => message.generatedReportId).filter(Boolean) as number[] | undefined, [details.data])
  const reports = useQuery({ queryKey: ['conversation-reports', reportIds], queryFn: async () => Promise.all((reportIds ?? []).map(reportApi.get)), enabled: Boolean(reportIds?.length) })
  const byId = useMemo(() => new Map(reports.data?.map((report) => [report.id, report]) ?? []), [reports.data])
  const query = useMutation({ mutationFn: () => assistantApi.query(question.trim(), selectedId), onMutate: () => setOptimisticQuestion(question.trim()), onSuccess: async (response) => { setQuestion(''); setSuggestions(response.suggestedQuestions); setOptimisticQuestion(''); setSelectedId(response.conversation.id); setParams({ conversation: String(response.conversation.id) }); await queryClient.invalidateQueries({ queryKey: ['conversations'] }); await queryClient.invalidateQueries({ queryKey: ['conversation', response.conversation.id] }); await queryClient.invalidateQueries({ queryKey: ['conversation-reports'] }); await queryClient.invalidateQueries({ queryKey: ['dashboard'] }) }, onError: (error) => { setOptimisticQuestion(''); toast.error(getProblemMessage(error)) } })
  const remove = useMutation({ mutationFn: conversationApi.remove, onSuccess: async () => { setSelectedId(undefined); setParams({}); await queryClient.invalidateQueries({ queryKey: ['conversations'] }); toast.success('Conversation deleted') } })
  useEffect(() => { if (selectedId) setParams({ conversation: String(selectedId) }); else setParams({}) }, [selectedId, setParams])

  const submit = (event: React.FormEvent) => { event.preventDefault(); if (question.trim() && !query.isPending) query.mutate() }
  const messages = details.data?.messages ?? []
  return <div className="-m-4 flex h-[calc(100vh-4.5rem)] overflow-hidden sm:-m-6 lg:-m-8">
    <aside className={`${mobileHistory ? 'fixed inset-y-0 left-0 z-50 flex w-80' : 'hidden'} flex-col border-r border-line bg-white p-3 lg:flex lg:w-72 dark:border-slate-800 dark:bg-slate-900`}><div className="flex items-center gap-2"><Button className="flex-1" onClick={() => { setSelectedId(undefined); setQuestion(''); setMobileHistory(false) }}><Plus size={17} />New conversation</Button><button className="rounded-lg p-2 lg:hidden" onClick={() => setMobileHistory(false)}>×</button></div><p className="px-2 pb-2 pt-6 text-xs font-bold uppercase tracking-wider text-ink-600 dark:text-slate-400">Recent conversations</p><div className="flex-1 space-y-1 overflow-y-auto">{conversations.data?.content.map((item) => <button key={item.id} onClick={() => { setSelectedId(item.id); setMobileHistory(false) }} className={`group flex w-full items-center gap-2 rounded-xl p-3 text-left text-sm ${selectedId === item.id ? 'bg-brand-100 text-brand-800 dark:bg-emerald-950 dark:text-emerald-200' : 'hover:bg-slate-100 dark:hover:bg-slate-800'}`}><span className="min-w-0 flex-1 truncate font-medium">{item.title}</span>{selectedId === item.id && <Trash2 size={15} className="text-red-500 opacity-0 group-hover:opacity-100" onClick={(event) => { event.stopPropagation(); if (window.confirm('Delete this conversation?')) remove.mutate(item.id) }} />}</button>)}</div></aside>
    {mobileHistory && <button className="fixed inset-0 z-40 bg-black/40 lg:hidden" onClick={() => setMobileHistory(false)} />}
    <section className="flex min-w-0 flex-1 flex-col bg-canvas dark:bg-slate-950"><header className="flex h-16 items-center border-b border-line bg-white px-4 dark:border-slate-800 dark:bg-slate-900"><button className="mr-3 lg:hidden" onClick={() => setMobileHistory(true)}><Menu /></button><div><h1 className="font-bold">FleetOps AI Assistant</h1><p className="text-xs text-ink-600 dark:text-slate-400">Validated reporting, not autonomous decision-making</p></div><StatusBadge tone="ai">AI</StatusBadge></header>
      <div className="flex-1 overflow-y-auto p-4 sm:p-6"><div className="mx-auto max-w-5xl space-y-6">{details.isLoading && <LoadingState label="Loading conversation" />}{details.isError && <ErrorState message={getProblemMessage(details.error)} />}{!selectedId && messages.length === 0 && <Welcome onSelect={setQuestion} />}{messages.map((message) => <MessageBlock key={message.id} message={message} report={message.generatedReportId ? byId.get(message.generatedReportId) : undefined} toast={toast} />)}{optimisticQuestion && <><ChatBubble author="USER" content={optimisticQuestion} /><div className="flex items-center gap-3 text-sm text-ai-700"><Bot className="animate-pulse" />Validating intent and calculating report…</div></>}{suggestions.length > 0 && <div className="ml-12"><p className="mb-2 text-xs font-bold uppercase tracking-wider text-ink-600 dark:text-slate-400">Suggested follow-ups</p><div className="flex flex-wrap gap-2">{suggestions.map((item) => <button className="focus-ring rounded-full border border-ai-100 bg-white px-3 py-2 text-xs font-semibold text-ai-700 hover:bg-ai-100 dark:border-violet-900 dark:bg-slate-900" key={item} onClick={() => setQuestion(item)}>{item}</button>)}</div></div>}</div></div>
      <form onSubmit={submit} className="border-t border-line bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="mx-auto flex max-w-5xl items-end gap-2"><textarea aria-label="Ask a fleet question" rows={2} maxLength={2000} value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); if (question.trim()) query.mutate() } }} placeholder="Example: Compare fuel consumption by vehicle this month" className="focus-ring min-h-14 flex-1 resize-none rounded-xl border border-line bg-slate-50 px-4 py-3 text-sm dark:border-slate-700 dark:bg-slate-950" /><Button aria-label="Send question" disabled={!question.trim() || query.isPending}><Send size={18} /><span className="hidden sm:inline">Ask</span></Button></div><p className="mx-auto mt-2 max-w-5xl text-xs text-ink-600 dark:text-slate-500">AI extracts report intent; calculations and access control remain deterministic.</p></form>
    </section>
  </div>
}

function Welcome({ onSelect }: { onSelect: (value: string) => void }) { const suggestions = ['Show fleet overview', 'Compare fuel consumption by vehicle this month', 'Show the highest maintenance cost vehicles', 'Show critical anomalies this week']; return <div className="py-12 text-center"><div className="mx-auto grid size-14 place-items-center rounded-2xl bg-ai-100 text-ai-700 dark:bg-violet-950 dark:text-violet-300"><Bot size={28} /></div><h2 className="mt-5 text-2xl font-bold">What would you like to understand?</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-ink-600 dark:text-slate-400">Ask a focused question about fleet operations. Dates, metrics, filters, and groupings will be validated before execution.</p><div className="mx-auto mt-8 grid max-w-2xl gap-3 sm:grid-cols-2">{suggestions.map((item) => <button onClick={() => onSelect(item)} className="focus-ring rounded-xl border border-line bg-white p-4 text-left text-sm font-semibold hover:border-ai-700 dark:border-slate-700 dark:bg-slate-900" key={item}>{item}</button>)}</div></div> }

function ChatBubble({ author, content }: { author: Message['author']; content: string }) { return <div className={`flex gap-3 ${author === 'USER' ? 'justify-end' : ''}`}>{author === 'ASSISTANT' && <div className="grid size-9 shrink-0 place-items-center rounded-full bg-ai-100 text-ai-700"><Bot size={18} /></div>}<div className={`max-w-3xl rounded-2xl px-4 py-3 text-sm leading-6 ${author === 'USER' ? 'bg-brand-700 text-white' : 'border border-line bg-white dark:border-slate-800 dark:bg-slate-900'}`}>{content}</div>{author === 'USER' && <div className="grid size-9 shrink-0 place-items-center rounded-full bg-brand-100 text-brand-800"><User size={18} /></div>}</div> }

function MessageBlock({ message, report, toast }: { message: Message; report?: GeneratedReport; toast: ReturnType<typeof useToast> }) { const client = useQueryClient(); return <div className="space-y-4"><ChatBubble author={message.author} content={message.content} />{message.author === 'ASSISTANT' && <div className="ml-12"><Button variant="ghost" className="px-2" onClick={async () => { await navigator.clipboard.writeText(message.content); toast.success('Answer copied') }}><Copy size={15} />Copy answer</Button></div>}{report && <div className="ml-0 space-y-3 lg:ml-12"><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={async () => { await reportApi.save(report.id, report.result?.title ?? 'Saved report'); toast.success('Report saved') }}><Save size={16} />Save</Button><Button variant="secondary" onClick={async () => { await reportApi.rerun(report.id); await client.invalidateQueries({ queryKey: ['conversation-reports'] }); toast.success('Report rerun with current data') }}><Play size={16} />Rerun</Button><Button variant="secondary" onClick={() => void downloadFile(`/reports/${report.id}/export/csv`)}><Download size={16} />CSV</Button><Button variant="secondary" onClick={() => void downloadFile(`/reports/${report.id}/export/pdf`)}><Download size={16} />PDF</Button></div><ReportView report={report} /></div>}</div> }
