import { useQuery } from '@tanstack/react-query'
import { AlertTriangle, Bot, Car, ClipboardCheck, FileText, Gauge, Users } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { dashboardApi } from '../api'
import { getProblemMessage } from '../api/client'
import { Button, EmptyState, ErrorState, formatDate, LoadingState, PageHeader, Panel, StatusBadge } from '../components/ui'

export function DashboardPage() {
  const navigate = useNavigate()
  const query = useQuery({ queryKey: ['dashboard'], queryFn: dashboardApi.get })
  if (query.isLoading) return <LoadingState label="Loading command center" />
  if (query.isError) return <ErrorState message={getProblemMessage(query.error)} retry={() => void query.refetch()} />
  const data = query.data!
  return <><PageHeader eyebrow="Command center" title="Reporting overview" description="A concise view of fleet health, reporting activity, and the fastest paths to insight." actions={<StatusBadge tone={data.fleetMode === 'MOCK' ? 'warning' : 'success'}>{data.fleetMode} fleet data</StatusBadge>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><Kpi icon={<Car />} label="Vehicles" value={data.fleet.totalVehicles} /><Kpi icon={<Gauge />} label="Active" value={data.fleet.activeVehicles} /><Kpi icon={<Users />} label="Drivers" value={data.fleet.activeDrivers} /><Kpi icon={<AlertTriangle />} label="Open anomalies" value={data.fleet.openAnomalies} danger={data.fleet.criticalOpenAnomalies > 0} /><Kpi icon={<FileText />} label="Reports" value={data.usage.generatedReports} /><Kpi icon={<ClipboardCheck />} label="Saved" value={data.usage.savedReports} /></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><Panel><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold">Ask FleetOps AI</h2><p className="mt-1 text-sm text-ink-600 dark:text-slate-400">Start with a supported operational question.</p></div><Bot className="text-ai-700" /></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{data.quickQuestions.map((question) => <button key={question} className="focus-ring rounded-xl border border-line p-3 text-left text-sm font-medium hover:border-brand-600 hover:bg-brand-100/40 dark:border-slate-700 dark:hover:bg-slate-800" onClick={() => navigate('/assistant', { state: { question } })}>{question}</button>)}</div><Link to="/assistant"><Button className="mt-5">Open AI assistant</Button></Link></Panel>
      <Panel><h2 className="text-lg font-bold">Reporting activity</h2><div className="mt-5 space-y-4">{data.reportUsageByType.length ? data.reportUsageByType.slice(0, 6).map((item) => <div key={item.reportType} className="flex items-center justify-between gap-3"><span className="truncate text-sm">{item.reportType.replaceAll('_', ' ')}</span><StatusBadge>{item.count}</StatusBadge></div>) : <p className="text-sm text-ink-600">Generate a report to begin tracking usage.</p>}</div></Panel></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-2"><Panel><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Recent reports</h2><Link className="text-sm font-semibold text-brand-700" to="/history">View history</Link></div><div className="mt-4 divide-y divide-line dark:divide-slate-800">{data.recentReports.length ? data.recentReports.map((report) => <Link to={`/reports/${report.id}`} key={report.id} className="flex items-center justify-between gap-3 py-3"><div className="min-w-0"><p className="truncate text-sm font-semibold">{report.result?.title ?? report.question}</p><p className="mt-1 text-xs text-ink-600 dark:text-slate-400">{formatDate(report.createdAt)}</p></div><StatusBadge tone={report.status === 'SUCCEEDED' ? 'success' : 'danger'}>{report.status}</StatusBadge></Link>) : <EmptyState title="No reports yet" description="Ask your first fleet question to create one." />}</div></Panel><Panel><h2 className="text-lg font-bold">Recent conversations</h2><div className="mt-4 divide-y divide-line dark:divide-slate-800">{data.recentConversations.length ? data.recentConversations.map((conversation) => <Link className="block py-3" to={`/assistant?conversation=${conversation.id}`} key={conversation.id}><p className="text-sm font-semibold">{conversation.title}</p><p className="mt-1 text-xs text-ink-600 dark:text-slate-400">Updated {formatDate(conversation.updatedAt)}</p></Link>) : <EmptyState title="No conversations" description="Conversations preserve the reasoning context around each report." />}</div></Panel></div>
  </>
}

function Kpi({ icon, label, value, danger = false }: { icon: React.ReactNode; label: string; value: number; danger?: boolean }) { return <Panel><div className={danger ? 'text-red-600' : 'text-brand-700'}>{icon}</div><p className="mt-4 text-2xl font-bold">{value}</p><p className="mt-1 text-xs font-semibold uppercase tracking-wider text-ink-600 dark:text-slate-400">{label}</p></Panel> }
